# this file will watch k8s for changes -- and will see every service file for changes
# no need to do kubectl apply -f k8s again and again

apiVersion: skaffold/v2beta16 
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/* # it will watch k8s for changes
      - ./infrastructure/k8s-dev/* # it will watch k8s for changes
build:
  local:
    push: false # every container we build will not be automatically deployed to dockerhub
  artifacts:
    - image: 03004968719/portal-auth
      context: auth # path to the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # every ts file in the src folder #? look style of this file
            dest: . # for putting the changes in the container
    - image: 03004968719/portal-accounts
      context: accounts # path to the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # every ts file in the src folder #? look style of this file
            dest: . # for putting the changes in the container
    - image: 03004968719/portal-courses
      context: courses # path to the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # every ts file in the src folder #? look style of this file
            dest: . # for putting the changes in the container
    - image: 03004968719/portal-expiration
      context: expiration # path to the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # every ts file in the src folder #? look style of this file
            dest: . # for putting the changes in the container
    - image: 03004968719/portal-client
      context: ssr-client # path to the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.jsx'
            dest: . # for putting the changes in the container

          - src: '**/*.tsx'
            dest: . # for putting the changes in the container
          
          - src: '**/*.scss'
            dest: . # for putting the changes in the container
  