apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: 03004968719/portal-expiration # this image is only built and not deployed
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: project1
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # we will get its own pod name - which is always unique
            - name: REDIS_HOST
              value: expiration-redis-srv
# here we don't want to expose this service to outside world as we don't have any route in this service
# so, no cluster ip service here