apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: 03004968719/portal-accounts # this image is only built and not deployed
          env:
            - name: MONGO_URI
              value: 'mongodb://accounts-mongo-srv:27017/accounts'
              #! we first need to have mongo-depl.yaml to make this work, its own db
              # in a k8s env, it is not an issue to hard coat this mongo uri because to access this,
              # someone would have to enter into the k8s cluster with my email account
              # but i can still use it as a secret
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: project1
---
# service config
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  # default type is cluster-ip-service
  selector:
    app: accounts
  ports:
    - name: accounts
      protocol: TCP
      port: 3000
      targetPort: 3000
